### ISSUE TITLE
vue-pagination-2 Combine with v-client page number issue in all browsers chrome IE 

### ISSUE THREAD

**Issue by qadirfarooq** [matfish2/vue-pagination-2#45]
- Vue.js version: 2
- consumed using: (browserify/webpack)
- FULL error message (including stack trace):
- relevant code:
- steps for reproducing the issue: 

V-client is using vue-pagination-2 underneath for pagination. what i found is all of the sudden its pagination look is bad. not sure if it break and where it breaks. the pagination width looks good but some how it doesn't arrange it in a single row.

**Comment by qadirfarooq** [comment]
trying to add screen shot but its not allow me to do so.

**Comment by matfish2** [comment]
Please see issue #44. I've made 2.0.3 latest in npm again and forced it on vue-tables-2. Try to install vue-tables-2 again and it should pull the correct version

**Comment by qadirfarooq** [comment]
i tired npm update vue-table-2 but its still pointing to vue-tables-2@1.6.25. any idea, i am totally new to this world?.

**Comment by cmitz** [comment]
> i tired npm update vue-table-2 but its still pointing to vue-tables-2@1.6.25. any idea, i am totally new to this world?.

I think @matfish2 means vue-pagination-2@v2.0.3, while vue-tables-2@v2.0.15 is the latest Vue Tables 2 release.

Since you mention that you're new to this. Let me try to help out a little:
You're not on the latest version, please update the vue-tables-2 entry in your `package.json` to 2.0.15.
If you still experience the UI looking all weird, please try to follow the Github Issue Template for this repository, and supply relevant code, maybe a screenshot and if you're seeing an error the full stack trace

**Comment by matfish2** [comment]
Upgraded pagination package. Vue tables 2 is now referencing the latest
